version = 0.1

[default.deploy.parameters]
stack_name = "second-brain"
resolve_s3 = true
s3_prefix = "second-brain"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "CognitoDomainPrefix=\"kinghacks2026\" GoogleDesktopClientId=\"889539163514-10nft2cs9sg6r66ssrusa649qm82kajr.apps.googleusercontent.com\""
image_repositories = []
disable_rollback = true

[default.global.parameters]
region = "us-east-1"
