version = 0.1

[default.deploy.parameters]
stack_name = "second-brain-backend-evan"
resolve_s3 = true
s3_prefix = "second-brain-backend-evan"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = false
parameter_overrides = "CognitoDomainPrefix=\"kinghacks2026-evan\" GoogleDesktopClientId=\"694425355162-33sjvpg98m6p3mtpa616p8ql5649gig4.apps.googleusercontent.com\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
